### ISSUE TITLE
Still Learning need help. Can't make it work using py3

### ISSUE THREAD

**Issue by Electrik-rich546456** [vierofernando/python-weather#5] opened 2021-05-16 19:41 UTC
Hi 
I can't seem to make this thing work.
I tried `git clone https://github.com/vierofernando/python-weather.git`
then `./setup.py`
and i receive this as a wonderful helpfull message :-)
```
`from: can't read /var/mail/setuptools
./setup.py: line 2: syntax error near unexpected token `newline'
./setup.py: line 2: `setup('
```

I also tried 
`pip3 install python-weather`
then copied the example and got this even more help...
```
Traceback (most recent call last):
  File "./watering_sys2.py", line 28, in <module>
    loop.run_until_complete(getweather())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./watering_sys2.py", line 11, in getweather
    weather = await client.find("northam")
  File "/home/user/.local/lib/python3.8/site-packages/python_weather/client.py", line 83, in find
    return Weather(content)
  File "/home/user/.local/lib/python3.8/site-packages/python_weather/weather.py", line 53, in __init__
    self.current               = Forecast._current(data["current"])
  File "/home/user/.local/lib/python3.8/site-packages/python_weather/forecast.py", line 47, in _current
    _class.date              = datetime.strptime(f'{data["@date"]} {data["@observationtime"]}', "%Y-%d-%m %H:%M:%S")
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2021-05-16 20:00:00' does not match format '%Y-%d-%m %H:%M:%S'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd3082be880>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd30729d5e0>, 37511.072011544)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd3082bedc0>
```
How do i fix it ?

**Comment by vierofernando** [comment] 2021-05-19 06:50
you are probably using an older version of `python-weather`, since the issue is already fixed in the most recent pull request (as of now)

**Closed** 2021-05-19 06:53 UTC
